version: '3.7'
services:

  starlette_context:
    image: starlette_context
    container_name: starlette_context
    build: .
    command: ['pytest', '.']
    ports:
      - 8080:8080
    expose:
      - 8080
    restart: always
